# Generated by Django 5.0.4 on 2026-06-02 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=19, unique=True)),
                ('external_card_id', models.CharField(max_length=64, unique=True)),
                ('masked_number', models.CharField(max_length=19)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='accounts.account')),
            ],
            options={
                'db_table': 'payment_cards',
            },
        ),
    ]
