# Generated by Django 5.0.4 on 2026-06-02 17:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_role_alter_user_groups_alter_user_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepaidCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('masked_number', models.CharField(max_length=19, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktywna'), ('BLOCKED', 'Zablokowana')], default='ACTIVE', max_length=10)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=500, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prepaid_card', to='accounts.account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepaid_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prepaid_cards',
            },
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('INTERNET', 'Płatność internetowa'), ('POS', 'Płatność kartą')], default='INTERNET', max_length=20)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Oczekuje na zgodę rodzica'), ('COMPLETED', 'Zrealizowana'), ('REJECTED', 'Odrzucona'), ('FAILED', 'Nieudana')], default='PENDING_APPROVAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_transactions', to='accounts.account')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='cards.prepaidcard')),
            ],
            options={
                'db_table': 'card_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
