# Generated by Django 5.0.4 on 2026-06-09 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('merchant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('AUTHORIZED', 'Zablokowano środki'), ('SETTLED', 'Zrealizowana'), ('REFUNDED', 'Zwrócona')], default='SETTLED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cards.paymentcard')),
            ],
            options={
                'db_table': 'card_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
