# Generated by Django 5.0.4 on 2026-06-02 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blik', '0002_phonealias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='P2pContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2p_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blik_p2p_contacts',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='p2pcontact',
            constraint=models.UniqueConstraint(fields=('user', 'phone'), name='uniq_p2p_contact_user_phone'),
        ),
    ]
