# Generated by Django 5.0.4 on 2026-06-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blik', '0003_p2pcontact_p2pcontact_uniq_p2p_contact_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bliktransaction',
            name='needs_parent_auth',
            field=models.BooleanField(default=False),
        ),
    ]
