# Generated by Django 5.0.4 on 2026-06-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blik_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
