# Generated by Django 5.0.4 on 2026-06-16 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_blik_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuniorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('blik_limit', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='junior_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'junior_profiles',
            },
        ),
    ]
