# Generated by Django 5.0.4 on 2026-06-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_transfer_scheduled_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='scheduled_at',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='system_route',
            field=models.CharField(choices=[('INTERNAL', 'Wewnętrzny'), ('ELIXIR', 'Elixir'), ('EXPRESS_ELIXIR', 'Express Elixir'), ('KLIK', 'KLIK'), ('SORBNET', 'Sorbnet')], default='ELIXIR', max_length=20),
        ),
    ]
