# Generated by Django 5.0.4 on 2026-06-02 17:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role_alter_user_groups_alter_user_is_active_and_more'),
        ('cards', '0001_initial'),
        ('transfers', '0003_remove_transfer_scheduled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Oczekujący'), ('PENDING_APPROVAL', 'Oczekuje na zgodę rodzica'), ('PROCESSING', 'W realizacji'), ('COMPLETED', 'Zrealizowany'), ('REJECTED', 'Odrzucony'), ('FAILED', 'Nieudany'), ('CANCELLED', 'Anulowany')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('TRANSFER', 'Przelew'), ('CARD_PAYMENT', 'Płatność kartą')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Oczekuje'), ('APPROVED', 'Zatwierdzony'), ('REJECTED', 'Odrzucony')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='accounts.account')),
                ('card_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_request', to='cards.cardtransaction')),
                ('junior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junior_approval_requests', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_approval_requests', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_request', to='transfers.transfer')),
            ],
            options={
                'db_table': 'approval_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
