# Generated by Django 5.0.4 on 2026-06-16 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_blik_pin'),
        ('transfers', '0004_alter_transfer_sender_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='sender_iban',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='sender_name',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to='accounts.account'),
        ),
    ]
