# Generated by Django 5.0.4 on 2026-06-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0005_remove_transfer_sender_iban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='swift_charge_bearer',
            field=models.CharField(blank=True, choices=[('OUR', 'OUR – Pokrywa nadawca'), ('SHA', 'SHA – Dzielone'), ('BEN', 'BEN – Pokrywa odbiorca')], help_text='Opcja podziału kosztów SWIFT (ChrgBr)', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='swift_uetr',
            field=models.UUIDField(blank=True, help_text='Unique End-to-end Transaction Reference (SWIFT GPI)', null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='system_route',
            field=models.CharField(choices=[('INTERNAL', 'Wewnętrzny'), ('ELIXIR', 'Elixir'), ('EXPRESS_ELIXIR', 'Express Elixir'), ('KLIK', 'KLIK'), ('SORBNET', 'Sorbnet'), ('SWIFT', 'SWIFT (Międzynarodowy)')], default='ELIXIR', max_length=20),
        ),
    ]
