# Generated by Django 5.0.4 on 2026-06-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0006_add_swift_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='aml_explanation',
            field=models.TextField(blank=True, help_text='Wyjaśnienie zablokowanego przelewu w ramach AML', null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Oczekujący'), ('AML_SUSPENDED', 'Wstrzymany (AML)'), ('PROCESSING', 'W realizacji'), ('COMPLETED', 'Zrealizowany'), ('FAILED', 'Nieudany'), ('CANCELLED', 'Anulowany')], default='PENDING', max_length=20),
        ),
    ]
