# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import card_pb2 as card__pb2


class CardProviderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCard = channel.unary_unary(
                '/cardprovider.CardProvider/CreateCard',
                request_serializer=card__pb2.CreateCardRequest.SerializeToString,
                response_deserializer=card__pb2.CreateCardResponse.FromString,
                )
        self.GetCardStatus = channel.unary_unary(
                '/cardprovider.CardProvider/GetCardStatus',
                request_serializer=card__pb2.GetCardRequest.SerializeToString,
                response_deserializer=card__pb2.CardDetails.FromString,
                )
        self.BlockCard = channel.unary_unary(
                '/cardprovider.CardProvider/BlockCard',
                request_serializer=card__pb2.BlockCardRequest.SerializeToString,
                response_deserializer=card__pb2.BlockCardResponse.FromString,
                )
        self.UnblockCard = channel.unary_unary(
                '/cardprovider.CardProvider/UnblockCard',
                request_serializer=card__pb2.UnblockCardRequest.SerializeToString,
                response_deserializer=card__pb2.UnblockCardResponse.FromString,
                )
        self.AuthorizeTransaction = channel.unary_unary(
                '/cardprovider.CardProvider/AuthorizeTransaction',
                request_serializer=card__pb2.AuthorizationRequest.SerializeToString,
                response_deserializer=card__pb2.AuthorizationResponse.FromString,
                )
        self.SettleTransaction = channel.unary_unary(
                '/cardprovider.CardProvider/SettleTransaction',
                request_serializer=card__pb2.SettlementRequest.SerializeToString,
                response_deserializer=card__pb2.SettlementResponse.FromString,
                )
        self.InitiateChargeback = channel.unary_unary(
                '/cardprovider.CardProvider/InitiateChargeback',
                request_serializer=card__pb2.ChargebackRequest.SerializeToString,
                response_deserializer=card__pb2.ChargebackResponse.FromString,
                )
        self.UpdateCardStatus = channel.unary_unary(
                '/cardprovider.CardProvider/UpdateCardStatus',
                request_serializer=card__pb2.UpdateCardStatusRequest.SerializeToString,
                response_deserializer=card__pb2.UpdateCardStatusResponse.FromString,
                )
        self.ActivateCard = channel.unary_unary(
                '/cardprovider.CardProvider/ActivateCard',
                request_serializer=card__pb2.ActivateCardRequest.SerializeToString,
                response_deserializer=card__pb2.ActivateCardResponse.FromString,
                )
        self.ListCards = channel.unary_unary(
                '/cardprovider.CardProvider/ListCards',
                request_serializer=card__pb2.ListCardsRequest.SerializeToString,
                response_deserializer=card__pb2.ListCardsResponse.FromString,
                )
        self.TopUpPrepaid = channel.unary_unary(
                '/cardprovider.CardProvider/TopUpPrepaid',
                request_serializer=card__pb2.TopUpRequest.SerializeToString,
                response_deserializer=card__pb2.TopUpResponse.FromString,
                )
        self.GetFullPan = channel.unary_unary(
                '/cardprovider.CardProvider/GetFullPan',
                request_serializer=card__pb2.GetCardRequest.SerializeToString,
                response_deserializer=card__pb2.FullPanResponse.FromString,
                )
        self.ProcessIsoMessage = channel.unary_unary(
                '/cardprovider.CardProvider/ProcessIsoMessage',
                request_serializer=card__pb2.IsoRequest.SerializeToString,
                response_deserializer=card__pb2.IsoResponse.FromString,
                )


class CardProviderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCardStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlockCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnblockCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthorizeTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SettleTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitiateChargeback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCardStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TopUpPrepaid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFullPan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessIsoMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CardProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCard': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCard,
                    request_deserializer=card__pb2.CreateCardRequest.FromString,
                    response_serializer=card__pb2.CreateCardResponse.SerializeToString,
            ),
            'GetCardStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCardStatus,
                    request_deserializer=card__pb2.GetCardRequest.FromString,
                    response_serializer=card__pb2.CardDetails.SerializeToString,
            ),
            'BlockCard': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockCard,
                    request_deserializer=card__pb2.BlockCardRequest.FromString,
                    response_serializer=card__pb2.BlockCardResponse.SerializeToString,
            ),
            'UnblockCard': grpc.unary_unary_rpc_method_handler(
                    servicer.UnblockCard,
                    request_deserializer=card__pb2.UnblockCardRequest.FromString,
                    response_serializer=card__pb2.UnblockCardResponse.SerializeToString,
            ),
            'AuthorizeTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthorizeTransaction,
                    request_deserializer=card__pb2.AuthorizationRequest.FromString,
                    response_serializer=card__pb2.AuthorizationResponse.SerializeToString,
            ),
            'SettleTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.SettleTransaction,
                    request_deserializer=card__pb2.SettlementRequest.FromString,
                    response_serializer=card__pb2.SettlementResponse.SerializeToString,
            ),
            'InitiateChargeback': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateChargeback,
                    request_deserializer=card__pb2.ChargebackRequest.FromString,
                    response_serializer=card__pb2.ChargebackResponse.SerializeToString,
            ),
            'UpdateCardStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCardStatus,
                    request_deserializer=card__pb2.UpdateCardStatusRequest.FromString,
                    response_serializer=card__pb2.UpdateCardStatusResponse.SerializeToString,
            ),
            'ActivateCard': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateCard,
                    request_deserializer=card__pb2.ActivateCardRequest.FromString,
                    response_serializer=card__pb2.ActivateCardResponse.SerializeToString,
            ),
            'ListCards': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCards,
                    request_deserializer=card__pb2.ListCardsRequest.FromString,
                    response_serializer=card__pb2.ListCardsResponse.SerializeToString,
            ),
            'TopUpPrepaid': grpc.unary_unary_rpc_method_handler(
                    servicer.TopUpPrepaid,
                    request_deserializer=card__pb2.TopUpRequest.FromString,
                    response_serializer=card__pb2.TopUpResponse.SerializeToString,
            ),
            'GetFullPan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFullPan,
                    request_deserializer=card__pb2.GetCardRequest.FromString,
                    response_serializer=card__pb2.FullPanResponse.SerializeToString,
            ),
            'ProcessIsoMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessIsoMessage,
                    request_deserializer=card__pb2.IsoRequest.FromString,
                    response_serializer=card__pb2.IsoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cardprovider.CardProvider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CardProvider(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cardprovider.CardProvider/CreateCard',
            card__pb2.CreateCardRequest.SerializeToString,
            card__pb2.CreateCardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCardStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cardprovider.CardProvider/GetCardStatus',
            card__pb2.GetCardRequest.SerializeToString,
            card__pb2.CardDetails.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BlockCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cardprovider.CardProvider/BlockCard',
            card__pb2.BlockCardRequest.SerializeToString,
            card__pb2.BlockCardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UnblockCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cardprovider.CardProvider/UnblockCard',
            card__pb2.UnblockCardRequest.SerializeToString,
            card__pb2.UnblockCardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AuthorizeTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cardprovider.CardProvider/AuthorizeTransaction',
            card__pb2.AuthorizationRequest.SerializeToString,
            card__pb2.AuthorizationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SettleTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cardprovider.CardProvider/SettleTransaction',
            card__pb2.SettlementRequest.SerializeToString,
            card__pb2.SettlementResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitiateChargeback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cardprovider.CardProvider/InitiateChargeback',
            card__pb2.ChargebackRequest.SerializeToString,
            card__pb2.ChargebackResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCardStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cardprovider.CardProvider/UpdateCardStatus',
            card__pb2.UpdateCardStatusRequest.SerializeToString,
            card__pb2.UpdateCardStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ActivateCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cardprovider.CardProvider/ActivateCard',
            card__pb2.ActivateCardRequest.SerializeToString,
            card__pb2.ActivateCardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListCards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cardprovider.CardProvider/ListCards',
            card__pb2.ListCardsRequest.SerializeToString,
            card__pb2.ListCardsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TopUpPrepaid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cardprovider.CardProvider/TopUpPrepaid',
            card__pb2.TopUpRequest.SerializeToString,
            card__pb2.TopUpResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFullPan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cardprovider.CardProvider/GetFullPan',
            card__pb2.GetCardRequest.SerializeToString,
            card__pb2.FullPanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProcessIsoMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cardprovider.CardProvider/ProcessIsoMessage',
            card__pb2.IsoRequest.SerializeToString,
            card__pb2.IsoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
